# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='E-mail')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution')),
                ('assistant', models.BooleanField(default=True, verbose_name='Will assist')),
                ('participant_hash', models.CharField(max_length=200, unique=True, verbose_name='Participant hash')),
                ('contribution', models.BooleanField(default=False, verbose_name='Contribution')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('link', models.URLField(blank=True, verbose_name='Contribution link')),
            ],
        ),
    ]
